social_networks:
#  twitter:
#    key: "UHMTtoPCi6Ej3aLpzOHQ"
#    secret: "BmtX68Wbo7PKjHcxZHi34xjV8OG1ZEwbXnvqbA1Ao"
  facebook:
    key: "663353313797273"                       # voyagex-local.info.tm:8080
    secret: "fce020bdf1f5ea03577a710bb2f69707"
